basePath: /api/v1
info:
  contact: {}
  description: 사물함 선착순 예약 시스템의 백엔드 API 문서
  title: Locker Reservation API
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    description: Bearer {access_token}
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
